/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * IPTV/OTT SaaS Platform API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary Get main dashboard statistics
 */
export declare const GetDashboardStatsResponse: zod.ZodObject<{
    totalClients: zod.ZodNumber;
    activeSubscriptions: zod.ZodNumber;
    monthlyRevenue: zod.ZodNumber;
    activeServers: zod.ZodNumber;
    newClientsThisMonth: zod.ZodNumber;
    churnRate: zod.ZodNumber;
    openTickets: zod.ZodNumber;
    totalResellers: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    totalClients: number;
    activeSubscriptions: number;
    monthlyRevenue: number;
    activeServers: number;
    newClientsThisMonth: number;
    churnRate: number;
    openTickets: number;
    totalResellers: number;
}, {
    totalClients: number;
    activeSubscriptions: number;
    monthlyRevenue: number;
    activeServers: number;
    newClientsThisMonth: number;
    churnRate: number;
    openTickets: number;
    totalResellers: number;
}>;
/**
 * @summary Get revenue chart data (last 12 months)
 */
export declare const GetRevenueChartResponseItem: zod.ZodObject<{
    month: zod.ZodString;
    revenue: zod.ZodNumber;
    subscriptions: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    month: string;
    revenue: number;
    subscriptions: number;
}, {
    month: string;
    revenue: number;
    subscriptions: number;
}>;
export declare const GetRevenueChartResponse: zod.ZodArray<zod.ZodObject<{
    month: zod.ZodString;
    revenue: zod.ZodNumber;
    subscriptions: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    month: string;
    revenue: number;
    subscriptions: number;
}, {
    month: string;
    revenue: number;
    subscriptions: number;
}>, "many">;
/**
 * @summary Get recent activity feed
 */
export declare const GetRecentActivityResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    type: zod.ZodString;
    description: zod.ZodString;
    clientName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    type: string;
    id: number;
    description: string;
    createdAt: string;
    clientName?: string | null | undefined;
}, {
    type: string;
    id: number;
    description: string;
    createdAt: string;
    clientName?: string | null | undefined;
}>;
export declare const GetRecentActivityResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    type: zod.ZodString;
    description: zod.ZodString;
    clientName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    type: string;
    id: number;
    description: string;
    createdAt: string;
    clientName?: string | null | undefined;
}, {
    type: string;
    id: number;
    description: string;
    createdAt: string;
    clientName?: string | null | undefined;
}>, "many">;
/**
 * @summary Get subscription status breakdown
 */
export declare const GetSubscriptionBreakdownResponseItem: zod.ZodObject<{
    status: zod.ZodString;
    count: zod.ZodNumber;
    percentage: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    status: string;
    count: number;
    percentage: number;
}, {
    status: string;
    count: number;
    percentage: number;
}>;
export declare const GetSubscriptionBreakdownResponse: zod.ZodArray<zod.ZodObject<{
    status: zod.ZodString;
    count: zod.ZodNumber;
    percentage: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    status: string;
    count: number;
    percentage: number;
}, {
    status: string;
    count: number;
    percentage: number;
}>, "many">;
/**
 * @summary List all clients
 */
export declare const ListClientsQueryParams: zod.ZodObject<{
    search: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodOptional<zod.ZodString>;
    page: zod.ZodOptional<zod.ZodNumber>;
    limit: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    status?: string | undefined;
    search?: string | undefined;
    page?: number | undefined;
    limit?: number | undefined;
}, {
    status?: string | undefined;
    search?: string | undefined;
    page?: number | undefined;
    limit?: number | undefined;
}>;
export declare const ListClientsResponse: zod.ZodObject<{
    data: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        email: zod.ZodString;
        phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        status: zod.ZodString;
        resellerId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        resellerName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        createdAt: zod.ZodString;
        updatedAt: zod.ZodOptional<zod.ZodString>;
    }, "strip", zod.ZodTypeAny, {
        status: string;
        id: number;
        createdAt: string;
        name: string;
        email: string;
        phone?: string | null | undefined;
        resellerId?: number | null | undefined;
        resellerName?: string | null | undefined;
        notes?: string | null | undefined;
        updatedAt?: string | undefined;
    }, {
        status: string;
        id: number;
        createdAt: string;
        name: string;
        email: string;
        phone?: string | null | undefined;
        resellerId?: number | null | undefined;
        resellerName?: string | null | undefined;
        notes?: string | null | undefined;
        updatedAt?: string | undefined;
    }>, "many">;
    total: zod.ZodNumber;
    page: zod.ZodNumber;
    limit: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    page: number;
    limit: number;
    data: {
        status: string;
        id: number;
        createdAt: string;
        name: string;
        email: string;
        phone?: string | null | undefined;
        resellerId?: number | null | undefined;
        resellerName?: string | null | undefined;
        notes?: string | null | undefined;
        updatedAt?: string | undefined;
    }[];
    total: number;
}, {
    page: number;
    limit: number;
    data: {
        status: string;
        id: number;
        createdAt: string;
        name: string;
        email: string;
        phone?: string | null | undefined;
        resellerId?: number | null | undefined;
        resellerName?: string | null | undefined;
        notes?: string | null | undefined;
        updatedAt?: string | undefined;
    }[];
    total: number;
}>;
/**
 * @summary Create a new client
 */
export declare const CreateClientBody: zod.ZodObject<{
    name: zod.ZodString;
    email: zod.ZodString;
    phone: zod.ZodOptional<zod.ZodString>;
    resellerId: zod.ZodOptional<zod.ZodNumber>;
    notes: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    email: string;
    phone?: string | undefined;
    resellerId?: number | undefined;
    notes?: string | undefined;
}, {
    name: string;
    email: string;
    phone?: string | undefined;
    resellerId?: number | undefined;
    notes?: string | undefined;
}>;
/**
 * @summary Get client by ID
 */
export declare const GetClientParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetClientResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    email: zod.ZodString;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodString;
    resellerId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    resellerName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
    updatedAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    email: string;
    phone?: string | null | undefined;
    resellerId?: number | null | undefined;
    resellerName?: string | null | undefined;
    notes?: string | null | undefined;
    updatedAt?: string | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    email: string;
    phone?: string | null | undefined;
    resellerId?: number | null | undefined;
    resellerName?: string | null | undefined;
    notes?: string | null | undefined;
    updatedAt?: string | undefined;
}>;
/**
 * @summary Update client
 */
export declare const UpdateClientParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateClientBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
    email: zod.ZodOptional<zod.ZodString>;
    phone: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodOptional<zod.ZodString>;
    resellerId: zod.ZodOptional<zod.ZodNumber>;
    notes: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status?: string | undefined;
    name?: string | undefined;
    email?: string | undefined;
    phone?: string | undefined;
    resellerId?: number | undefined;
    notes?: string | undefined;
}, {
    status?: string | undefined;
    name?: string | undefined;
    email?: string | undefined;
    phone?: string | undefined;
    resellerId?: number | undefined;
    notes?: string | undefined;
}>;
export declare const UpdateClientResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    email: zod.ZodString;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodString;
    resellerId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    resellerName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
    updatedAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    email: string;
    phone?: string | null | undefined;
    resellerId?: number | null | undefined;
    resellerName?: string | null | undefined;
    notes?: string | null | undefined;
    updatedAt?: string | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    email: string;
    phone?: string | null | undefined;
    resellerId?: number | null | undefined;
    resellerName?: string | null | undefined;
    notes?: string | null | undefined;
    updatedAt?: string | undefined;
}>;
/**
 * @summary Delete client
 */
export declare const DeleteClientParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary Suspend client account
 */
export declare const SuspendClientParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const SuspendClientResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    email: zod.ZodString;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodString;
    resellerId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    resellerName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
    updatedAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    email: string;
    phone?: string | null | undefined;
    resellerId?: number | null | undefined;
    resellerName?: string | null | undefined;
    notes?: string | null | undefined;
    updatedAt?: string | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    email: string;
    phone?: string | null | undefined;
    resellerId?: number | null | undefined;
    resellerName?: string | null | undefined;
    notes?: string | null | undefined;
    updatedAt?: string | undefined;
}>;
/**
 * @summary Activate client account
 */
export declare const ActivateClientParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const ActivateClientResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    email: zod.ZodString;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodString;
    resellerId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    resellerName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
    updatedAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    email: string;
    phone?: string | null | undefined;
    resellerId?: number | null | undefined;
    resellerName?: string | null | undefined;
    notes?: string | null | undefined;
    updatedAt?: string | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    email: string;
    phone?: string | null | undefined;
    resellerId?: number | null | undefined;
    resellerName?: string | null | undefined;
    notes?: string | null | undefined;
    updatedAt?: string | undefined;
}>;
/**
 * @summary Bulk import clients from CSV data
 */
export declare const ImportClientsBody: zod.ZodObject<{
    csv: zod.ZodString;
    skipErrors: zod.ZodOptional<zod.ZodBoolean>;
}, "strip", zod.ZodTypeAny, {
    csv: string;
    skipErrors?: boolean | undefined;
}, {
    csv: string;
    skipErrors?: boolean | undefined;
}>;
export declare const ImportClientsResponse: zod.ZodObject<{
    imported: zod.ZodNumber;
    skipped: zod.ZodNumber;
    errors: zod.ZodArray<zod.ZodObject<{
        row: zod.ZodNumber;
        reason: zod.ZodString;
        data: zod.ZodOptional<zod.ZodString>;
    }, "strip", zod.ZodTypeAny, {
        row: number;
        reason: string;
        data?: string | undefined;
    }, {
        row: number;
        reason: string;
        data?: string | undefined;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    imported: number;
    skipped: number;
    errors: {
        row: number;
        reason: string;
        data?: string | undefined;
    }[];
}, {
    imported: number;
    skipped: number;
    errors: {
        row: number;
        reason: string;
        data?: string | undefined;
    }[];
}>;
/**
 * @summary List all plans
 */
export declare const ListPlansResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    durationDays: zod.ZodNumber;
    maxConnections: zod.ZodNumber;
    features: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    creditCost: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    status: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    price: number;
    durationDays: number;
    maxConnections: number;
    description?: string | null | undefined;
    features?: string | null | undefined;
    creditCost?: number | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    price: number;
    durationDays: number;
    maxConnections: number;
    description?: string | null | undefined;
    features?: string | null | undefined;
    creditCost?: number | null | undefined;
}>;
export declare const ListPlansResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    durationDays: zod.ZodNumber;
    maxConnections: zod.ZodNumber;
    features: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    creditCost: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    status: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    price: number;
    durationDays: number;
    maxConnections: number;
    description?: string | null | undefined;
    features?: string | null | undefined;
    creditCost?: number | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    price: number;
    durationDays: number;
    maxConnections: number;
    description?: string | null | undefined;
    features?: string | null | undefined;
    creditCost?: number | null | undefined;
}>, "many">;
/**
 * @summary Create a new plan
 */
export declare const CreatePlanBody: zod.ZodObject<{
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodString>;
    price: zod.ZodNumber;
    durationDays: zod.ZodNumber;
    maxConnections: zod.ZodNumber;
    features: zod.ZodOptional<zod.ZodString>;
    creditCost: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    price: number;
    durationDays: number;
    maxConnections: number;
    description?: string | undefined;
    features?: string | undefined;
    creditCost?: number | undefined;
}, {
    name: string;
    price: number;
    durationDays: number;
    maxConnections: number;
    description?: string | undefined;
    features?: string | undefined;
    creditCost?: number | undefined;
}>;
/**
 * @summary Get plan by ID
 */
export declare const GetPlanParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetPlanResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    durationDays: zod.ZodNumber;
    maxConnections: zod.ZodNumber;
    features: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    creditCost: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    status: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    price: number;
    durationDays: number;
    maxConnections: number;
    description?: string | null | undefined;
    features?: string | null | undefined;
    creditCost?: number | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    price: number;
    durationDays: number;
    maxConnections: number;
    description?: string | null | undefined;
    features?: string | null | undefined;
    creditCost?: number | null | undefined;
}>;
/**
 * @summary Update plan
 */
export declare const UpdatePlanParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdatePlanBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
    description: zod.ZodOptional<zod.ZodString>;
    price: zod.ZodOptional<zod.ZodNumber>;
    durationDays: zod.ZodOptional<zod.ZodNumber>;
    maxConnections: zod.ZodOptional<zod.ZodNumber>;
    features: zod.ZodOptional<zod.ZodString>;
    creditCost: zod.ZodOptional<zod.ZodNumber>;
    status: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status?: string | undefined;
    description?: string | undefined;
    name?: string | undefined;
    price?: number | undefined;
    durationDays?: number | undefined;
    maxConnections?: number | undefined;
    features?: string | undefined;
    creditCost?: number | undefined;
}, {
    status?: string | undefined;
    description?: string | undefined;
    name?: string | undefined;
    price?: number | undefined;
    durationDays?: number | undefined;
    maxConnections?: number | undefined;
    features?: string | undefined;
    creditCost?: number | undefined;
}>;
export declare const UpdatePlanResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    durationDays: zod.ZodNumber;
    maxConnections: zod.ZodNumber;
    features: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    creditCost: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    status: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    price: number;
    durationDays: number;
    maxConnections: number;
    description?: string | null | undefined;
    features?: string | null | undefined;
    creditCost?: number | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    price: number;
    durationDays: number;
    maxConnections: number;
    description?: string | null | undefined;
    features?: string | null | undefined;
    creditCost?: number | null | undefined;
}>;
/**
 * @summary Delete plan
 */
export declare const DeletePlanParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary List all subscriptions
 */
export declare const ListSubscriptionsQueryParams: zod.ZodObject<{
    status: zod.ZodOptional<zod.ZodString>;
    clientId: zod.ZodOptional<zod.ZodNumber>;
    page: zod.ZodOptional<zod.ZodNumber>;
    limit: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    status?: string | undefined;
    page?: number | undefined;
    limit?: number | undefined;
    clientId?: number | undefined;
}, {
    status?: string | undefined;
    page?: number | undefined;
    limit?: number | undefined;
    clientId?: number | undefined;
}>;
export declare const ListSubscriptionsResponse: zod.ZodObject<{
    data: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        clientId: zod.ZodNumber;
        clientName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        planId: zod.ZodNumber;
        planName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        serverId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        serverName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        status: zod.ZodString;
        username: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        password: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        startDate: zod.ZodString;
        endDate: zod.ZodString;
        createdAt: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        status: string;
        id: number;
        createdAt: string;
        clientId: number;
        planId: number;
        startDate: string;
        endDate: string;
        clientName?: string | null | undefined;
        planName?: string | null | undefined;
        serverId?: number | null | undefined;
        serverName?: string | null | undefined;
        username?: string | null | undefined;
        password?: string | null | undefined;
    }, {
        status: string;
        id: number;
        createdAt: string;
        clientId: number;
        planId: number;
        startDate: string;
        endDate: string;
        clientName?: string | null | undefined;
        planName?: string | null | undefined;
        serverId?: number | null | undefined;
        serverName?: string | null | undefined;
        username?: string | null | undefined;
        password?: string | null | undefined;
    }>, "many">;
    total: zod.ZodNumber;
    page: zod.ZodNumber;
    limit: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    page: number;
    limit: number;
    data: {
        status: string;
        id: number;
        createdAt: string;
        clientId: number;
        planId: number;
        startDate: string;
        endDate: string;
        clientName?: string | null | undefined;
        planName?: string | null | undefined;
        serverId?: number | null | undefined;
        serverName?: string | null | undefined;
        username?: string | null | undefined;
        password?: string | null | undefined;
    }[];
    total: number;
}, {
    page: number;
    limit: number;
    data: {
        status: string;
        id: number;
        createdAt: string;
        clientId: number;
        planId: number;
        startDate: string;
        endDate: string;
        clientName?: string | null | undefined;
        planName?: string | null | undefined;
        serverId?: number | null | undefined;
        serverName?: string | null | undefined;
        username?: string | null | undefined;
        password?: string | null | undefined;
    }[];
    total: number;
}>;
/**
 * @summary Create a new subscription
 */
export declare const CreateSubscriptionBody: zod.ZodObject<{
    clientId: zod.ZodNumber;
    planId: zod.ZodNumber;
    serverId: zod.ZodOptional<zod.ZodNumber>;
    username: zod.ZodOptional<zod.ZodString>;
    password: zod.ZodOptional<zod.ZodString>;
    startDate: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    clientId: number;
    planId: number;
    startDate: string;
    serverId?: number | undefined;
    username?: string | undefined;
    password?: string | undefined;
}, {
    clientId: number;
    planId: number;
    startDate: string;
    serverId?: number | undefined;
    username?: string | undefined;
    password?: string | undefined;
}>;
/**
 * @summary Get subscription by ID
 */
export declare const GetSubscriptionParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetSubscriptionResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    clientId: zod.ZodNumber;
    clientName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    planId: zod.ZodNumber;
    planName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    serverId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    serverName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodString;
    username: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    password: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    startDate: zod.ZodString;
    endDate: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    clientId: number;
    planId: number;
    startDate: string;
    endDate: string;
    clientName?: string | null | undefined;
    planName?: string | null | undefined;
    serverId?: number | null | undefined;
    serverName?: string | null | undefined;
    username?: string | null | undefined;
    password?: string | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    clientId: number;
    planId: number;
    startDate: string;
    endDate: string;
    clientName?: string | null | undefined;
    planName?: string | null | undefined;
    serverId?: number | null | undefined;
    serverName?: string | null | undefined;
    username?: string | null | undefined;
    password?: string | null | undefined;
}>;
/**
 * @summary Update subscription
 */
export declare const UpdateSubscriptionParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateSubscriptionBody: zod.ZodObject<{
    planId: zod.ZodOptional<zod.ZodNumber>;
    serverId: zod.ZodOptional<zod.ZodNumber>;
    status: zod.ZodOptional<zod.ZodString>;
    username: zod.ZodOptional<zod.ZodString>;
    password: zod.ZodOptional<zod.ZodString>;
    endDate: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status?: string | undefined;
    planId?: number | undefined;
    serverId?: number | undefined;
    username?: string | undefined;
    password?: string | undefined;
    endDate?: string | undefined;
}, {
    status?: string | undefined;
    planId?: number | undefined;
    serverId?: number | undefined;
    username?: string | undefined;
    password?: string | undefined;
    endDate?: string | undefined;
}>;
export declare const UpdateSubscriptionResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    clientId: zod.ZodNumber;
    clientName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    planId: zod.ZodNumber;
    planName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    serverId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    serverName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodString;
    username: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    password: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    startDate: zod.ZodString;
    endDate: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    clientId: number;
    planId: number;
    startDate: string;
    endDate: string;
    clientName?: string | null | undefined;
    planName?: string | null | undefined;
    serverId?: number | null | undefined;
    serverName?: string | null | undefined;
    username?: string | null | undefined;
    password?: string | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    clientId: number;
    planId: number;
    startDate: string;
    endDate: string;
    clientName?: string | null | undefined;
    planName?: string | null | undefined;
    serverId?: number | null | undefined;
    serverName?: string | null | undefined;
    username?: string | null | undefined;
    password?: string | null | undefined;
}>;
/**
 * @summary Cancel subscription
 */
export declare const DeleteSubscriptionParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary Renew subscription
 */
export declare const RenewSubscriptionParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const RenewSubscriptionResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    clientId: zod.ZodNumber;
    clientName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    planId: zod.ZodNumber;
    planName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    serverId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    serverName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodString;
    username: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    password: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    startDate: zod.ZodString;
    endDate: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    clientId: number;
    planId: number;
    startDate: string;
    endDate: string;
    clientName?: string | null | undefined;
    planName?: string | null | undefined;
    serverId?: number | null | undefined;
    serverName?: string | null | undefined;
    username?: string | null | undefined;
    password?: string | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    clientId: number;
    planId: number;
    startDate: string;
    endDate: string;
    clientName?: string | null | undefined;
    planName?: string | null | undefined;
    serverId?: number | null | undefined;
    serverName?: string | null | undefined;
    username?: string | null | undefined;
    password?: string | null | undefined;
}>;
/**
 * @summary List all IPTV servers
 */
export declare const ListServersResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    host: zod.ZodString;
    port: zod.ZodNumber;
    username: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    password: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodString;
    maxConnections: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    activeStreams: zod.ZodOptional<zod.ZodNumber>;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    host: string;
    port: number;
    maxConnections?: number | null | undefined;
    username?: string | null | undefined;
    password?: string | null | undefined;
    activeStreams?: number | undefined;
    location?: string | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    host: string;
    port: number;
    maxConnections?: number | null | undefined;
    username?: string | null | undefined;
    password?: string | null | undefined;
    activeStreams?: number | undefined;
    location?: string | null | undefined;
}>;
export declare const ListServersResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    host: zod.ZodString;
    port: zod.ZodNumber;
    username: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    password: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodString;
    maxConnections: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    activeStreams: zod.ZodOptional<zod.ZodNumber>;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    host: string;
    port: number;
    maxConnections?: number | null | undefined;
    username?: string | null | undefined;
    password?: string | null | undefined;
    activeStreams?: number | undefined;
    location?: string | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    host: string;
    port: number;
    maxConnections?: number | null | undefined;
    username?: string | null | undefined;
    password?: string | null | undefined;
    activeStreams?: number | undefined;
    location?: string | null | undefined;
}>, "many">;
/**
 * @summary Add a new IPTV server
 */
export declare const CreateServerBody: zod.ZodObject<{
    name: zod.ZodString;
    host: zod.ZodString;
    port: zod.ZodNumber;
    username: zod.ZodOptional<zod.ZodString>;
    password: zod.ZodOptional<zod.ZodString>;
    maxConnections: zod.ZodOptional<zod.ZodNumber>;
    location: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    host: string;
    port: number;
    maxConnections?: number | undefined;
    username?: string | undefined;
    password?: string | undefined;
    location?: string | undefined;
}, {
    name: string;
    host: string;
    port: number;
    maxConnections?: number | undefined;
    username?: string | undefined;
    password?: string | undefined;
    location?: string | undefined;
}>;
/**
 * @summary Get server by ID
 */
export declare const GetServerParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetServerResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    host: zod.ZodString;
    port: zod.ZodNumber;
    username: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    password: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodString;
    maxConnections: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    activeStreams: zod.ZodOptional<zod.ZodNumber>;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    host: string;
    port: number;
    maxConnections?: number | null | undefined;
    username?: string | null | undefined;
    password?: string | null | undefined;
    activeStreams?: number | undefined;
    location?: string | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    host: string;
    port: number;
    maxConnections?: number | null | undefined;
    username?: string | null | undefined;
    password?: string | null | undefined;
    activeStreams?: number | undefined;
    location?: string | null | undefined;
}>;
/**
 * @summary Update server
 */
export declare const UpdateServerParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateServerBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
    host: zod.ZodOptional<zod.ZodString>;
    port: zod.ZodOptional<zod.ZodNumber>;
    username: zod.ZodOptional<zod.ZodString>;
    password: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodOptional<zod.ZodString>;
    maxConnections: zod.ZodOptional<zod.ZodNumber>;
    location: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status?: string | undefined;
    name?: string | undefined;
    maxConnections?: number | undefined;
    username?: string | undefined;
    password?: string | undefined;
    host?: string | undefined;
    port?: number | undefined;
    location?: string | undefined;
}, {
    status?: string | undefined;
    name?: string | undefined;
    maxConnections?: number | undefined;
    username?: string | undefined;
    password?: string | undefined;
    host?: string | undefined;
    port?: number | undefined;
    location?: string | undefined;
}>;
export declare const UpdateServerResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    host: zod.ZodString;
    port: zod.ZodNumber;
    username: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    password: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodString;
    maxConnections: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    activeStreams: zod.ZodOptional<zod.ZodNumber>;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    host: string;
    port: number;
    maxConnections?: number | null | undefined;
    username?: string | null | undefined;
    password?: string | null | undefined;
    activeStreams?: number | undefined;
    location?: string | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    host: string;
    port: number;
    maxConnections?: number | null | undefined;
    username?: string | null | undefined;
    password?: string | null | undefined;
    activeStreams?: number | undefined;
    location?: string | null | undefined;
}>;
/**
 * @summary Delete server
 */
export declare const DeleteServerParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary Get health metrics for all IPTV servers
 */
export declare const GetServersHealthResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    host: zod.ZodString;
    port: zod.ZodNumber;
    status: zod.ZodString;
    location: zod.ZodNullable<zod.ZodString>;
    activeStreams: zod.ZodNumber;
    maxConnections: zod.ZodNullable<zod.ZodNumber>;
    loadPct: zod.ZodNumber;
    latencyMs: zod.ZodNullable<zod.ZodNumber>;
    checkedAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    name: string;
    maxConnections: number | null;
    host: string;
    port: number;
    activeStreams: number;
    location: string | null;
    loadPct: number;
    latencyMs: number | null;
    checkedAt: string;
}, {
    status: string;
    id: number;
    name: string;
    maxConnections: number | null;
    host: string;
    port: number;
    activeStreams: number;
    location: string | null;
    loadPct: number;
    latencyMs: number | null;
    checkedAt: string;
}>;
export declare const GetServersHealthResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    host: zod.ZodString;
    port: zod.ZodNumber;
    status: zod.ZodString;
    location: zod.ZodNullable<zod.ZodString>;
    activeStreams: zod.ZodNumber;
    maxConnections: zod.ZodNullable<zod.ZodNumber>;
    loadPct: zod.ZodNumber;
    latencyMs: zod.ZodNullable<zod.ZodNumber>;
    checkedAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    name: string;
    maxConnections: number | null;
    host: string;
    port: number;
    activeStreams: number;
    location: string | null;
    loadPct: number;
    latencyMs: number | null;
    checkedAt: string;
}, {
    status: string;
    id: number;
    name: string;
    maxConnections: number | null;
    host: string;
    port: number;
    activeStreams: number;
    location: string | null;
    loadPct: number;
    latencyMs: number | null;
    checkedAt: string;
}>, "many">;
/**
 * @summary Test server connectivity
 */
export declare const TestServerParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const TestServerResponse: zod.ZodObject<{
    online: zod.ZodBoolean;
    latencyMs: zod.ZodNullable<zod.ZodNumber>;
    message: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    message: string;
    latencyMs: number | null;
    online: boolean;
}, {
    message: string;
    latencyMs: number | null;
    online: boolean;
}>;
/**
 * @summary List all resellers
 */
export declare const ListResellersQueryParams: zod.ZodObject<{
    search: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodOptional<zod.ZodString>;
    page: zod.ZodOptional<zod.ZodNumber>;
    limit: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    status?: string | undefined;
    search?: string | undefined;
    page?: number | undefined;
    limit?: number | undefined;
}, {
    status?: string | undefined;
    search?: string | undefined;
    page?: number | undefined;
    limit?: number | undefined;
}>;
export declare const ListResellersResponse: zod.ZodObject<{
    data: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        email: zod.ZodString;
        phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        status: zod.ZodString;
        creditBalance: zod.ZodNumber;
        totalClients: zod.ZodOptional<zod.ZodNumber>;
        notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        createdAt: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        status: string;
        id: number;
        createdAt: string;
        name: string;
        email: string;
        creditBalance: number;
        totalClients?: number | undefined;
        phone?: string | null | undefined;
        notes?: string | null | undefined;
    }, {
        status: string;
        id: number;
        createdAt: string;
        name: string;
        email: string;
        creditBalance: number;
        totalClients?: number | undefined;
        phone?: string | null | undefined;
        notes?: string | null | undefined;
    }>, "many">;
    total: zod.ZodNumber;
    page: zod.ZodNumber;
    limit: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    page: number;
    limit: number;
    data: {
        status: string;
        id: number;
        createdAt: string;
        name: string;
        email: string;
        creditBalance: number;
        totalClients?: number | undefined;
        phone?: string | null | undefined;
        notes?: string | null | undefined;
    }[];
    total: number;
}, {
    page: number;
    limit: number;
    data: {
        status: string;
        id: number;
        createdAt: string;
        name: string;
        email: string;
        creditBalance: number;
        totalClients?: number | undefined;
        phone?: string | null | undefined;
        notes?: string | null | undefined;
    }[];
    total: number;
}>;
/**
 * @summary Create a new reseller
 */
export declare const CreateResellerBody: zod.ZodObject<{
    name: zod.ZodString;
    email: zod.ZodString;
    phone: zod.ZodOptional<zod.ZodString>;
    creditBalance: zod.ZodOptional<zod.ZodNumber>;
    notes: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    email: string;
    phone?: string | undefined;
    notes?: string | undefined;
    creditBalance?: number | undefined;
}, {
    name: string;
    email: string;
    phone?: string | undefined;
    notes?: string | undefined;
    creditBalance?: number | undefined;
}>;
/**
 * @summary Get reseller by ID
 */
export declare const GetResellerParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetResellerResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    email: zod.ZodString;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodString;
    creditBalance: zod.ZodNumber;
    totalClients: zod.ZodOptional<zod.ZodNumber>;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    email: string;
    creditBalance: number;
    totalClients?: number | undefined;
    phone?: string | null | undefined;
    notes?: string | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    email: string;
    creditBalance: number;
    totalClients?: number | undefined;
    phone?: string | null | undefined;
    notes?: string | null | undefined;
}>;
/**
 * @summary Update reseller
 */
export declare const UpdateResellerParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateResellerBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
    email: zod.ZodOptional<zod.ZodString>;
    phone: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodOptional<zod.ZodString>;
    notes: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status?: string | undefined;
    name?: string | undefined;
    email?: string | undefined;
    phone?: string | undefined;
    notes?: string | undefined;
}, {
    status?: string | undefined;
    name?: string | undefined;
    email?: string | undefined;
    phone?: string | undefined;
    notes?: string | undefined;
}>;
export declare const UpdateResellerResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    email: zod.ZodString;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodString;
    creditBalance: zod.ZodNumber;
    totalClients: zod.ZodOptional<zod.ZodNumber>;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    email: string;
    creditBalance: number;
    totalClients?: number | undefined;
    phone?: string | null | undefined;
    notes?: string | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    email: string;
    creditBalance: number;
    totalClients?: number | undefined;
    phone?: string | null | undefined;
    notes?: string | null | undefined;
}>;
/**
 * @summary Delete reseller
 */
export declare const DeleteResellerParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary Adjust reseller credit balance
 */
export declare const AdjustResellerCreditsParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const AdjustResellerCreditsBody: zod.ZodObject<{
    amount: zod.ZodNumber;
    reason: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    reason: string;
    amount: number;
}, {
    reason: string;
    amount: number;
}>;
export declare const AdjustResellerCreditsResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    email: zod.ZodString;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodString;
    creditBalance: zod.ZodNumber;
    totalClients: zod.ZodOptional<zod.ZodNumber>;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    email: string;
    creditBalance: number;
    totalClients?: number | undefined;
    phone?: string | null | undefined;
    notes?: string | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    name: string;
    email: string;
    creditBalance: number;
    totalClients?: number | undefined;
    phone?: string | null | undefined;
    notes?: string | null | undefined;
}>;
/**
 * @summary Get platform settings
 */
export declare const GetSettingsResponse: zod.ZodObject<{
    operationMode: zod.ZodString;
    creditCurrencyName: zod.ZodString;
    creditToMoneyRate: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    operationMode: string;
    creditCurrencyName: string;
    creditToMoneyRate: number;
}, {
    operationMode: string;
    creditCurrencyName: string;
    creditToMoneyRate: number;
}>;
/**
 * @summary Update platform settings
 */
export declare const UpdateSettingsBody: zod.ZodObject<{
    operationMode: zod.ZodOptional<zod.ZodString>;
    creditCurrencyName: zod.ZodOptional<zod.ZodString>;
    creditToMoneyRate: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    operationMode?: string | undefined;
    creditCurrencyName?: string | undefined;
    creditToMoneyRate?: number | undefined;
}, {
    operationMode?: string | undefined;
    creditCurrencyName?: string | undefined;
    creditToMoneyRate?: number | undefined;
}>;
export declare const UpdateSettingsResponse: zod.ZodObject<{
    operationMode: zod.ZodString;
    creditCurrencyName: zod.ZodString;
    creditToMoneyRate: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    operationMode: string;
    creditCurrencyName: string;
    creditToMoneyRate: number;
}, {
    operationMode: string;
    creditCurrencyName: string;
    creditToMoneyRate: number;
}>;
/**
 * @summary List all credit transactions
 */
export declare const ListCreditTransactionsQueryParams: zod.ZodObject<{
    resellerId: zod.ZodOptional<zod.ZodNumber>;
    type: zod.ZodOptional<zod.ZodString>;
    page: zod.ZodOptional<zod.ZodNumber>;
    limit: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    type?: string | undefined;
    page?: number | undefined;
    limit?: number | undefined;
    resellerId?: number | undefined;
}, {
    type?: string | undefined;
    page?: number | undefined;
    limit?: number | undefined;
    resellerId?: number | undefined;
}>;
export declare const ListCreditTransactionsResponse: zod.ZodObject<{
    data: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        resellerId: zod.ZodNumber;
        resellerName: zod.ZodString;
        type: zod.ZodString;
        amount: zod.ZodNumber;
        balanceAfter: zod.ZodNumber;
        description: zod.ZodString;
        createdAt: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        type: string;
        id: number;
        description: string;
        createdAt: string;
        resellerId: number;
        resellerName: string;
        amount: number;
        balanceAfter: number;
    }, {
        type: string;
        id: number;
        description: string;
        createdAt: string;
        resellerId: number;
        resellerName: string;
        amount: number;
        balanceAfter: number;
    }>, "many">;
    total: zod.ZodNumber;
    page: zod.ZodNumber;
    limit: zod.ZodNumber;
    totalPurchased: zod.ZodNumber;
    totalDeducted: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    page: number;
    limit: number;
    data: {
        type: string;
        id: number;
        description: string;
        createdAt: string;
        resellerId: number;
        resellerName: string;
        amount: number;
        balanceAfter: number;
    }[];
    total: number;
    totalPurchased: number;
    totalDeducted: number;
}, {
    page: number;
    limit: number;
    data: {
        type: string;
        id: number;
        description: string;
        createdAt: string;
        resellerId: number;
        resellerName: string;
        amount: number;
        balanceAfter: number;
    }[];
    total: number;
    totalPurchased: number;
    totalDeducted: number;
}>;
/**
 * @summary Get credit summary stats
 */
export declare const GetCreditSummaryResponse: zod.ZodObject<{
    totalCreditsInCirculation: zod.ZodNumber;
    purchasedThisMonth: zod.ZodNumber;
    deductedThisMonth: zod.ZodNumber;
    topResellers: zod.ZodArray<zod.ZodObject<{
        resellerId: zod.ZodNumber;
        resellerName: zod.ZodString;
        creditBalance: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        resellerId: number;
        resellerName: string;
        creditBalance: number;
    }, {
        resellerId: number;
        resellerName: string;
        creditBalance: number;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    totalCreditsInCirculation: number;
    purchasedThisMonth: number;
    deductedThisMonth: number;
    topResellers: {
        resellerId: number;
        resellerName: string;
        creditBalance: number;
    }[];
}, {
    totalCreditsInCirculation: number;
    purchasedThisMonth: number;
    deductedThisMonth: number;
    topResellers: {
        resellerId: number;
        resellerName: string;
        creditBalance: number;
    }[];
}>;
/**
 * @summary List all invoices
 */
export declare const ListInvoicesQueryParams: zod.ZodObject<{
    status: zod.ZodOptional<zod.ZodString>;
    clientId: zod.ZodOptional<zod.ZodNumber>;
    page: zod.ZodOptional<zod.ZodNumber>;
    limit: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    status?: string | undefined;
    page?: number | undefined;
    limit?: number | undefined;
    clientId?: number | undefined;
}, {
    status?: string | undefined;
    page?: number | undefined;
    limit?: number | undefined;
    clientId?: number | undefined;
}>;
export declare const ListInvoicesResponse: zod.ZodObject<{
    data: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        clientId: zod.ZodNumber;
        clientName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        amount: zod.ZodNumber;
        status: zod.ZodString;
        description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        dueDate: zod.ZodString;
        paidAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        createdAt: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        status: string;
        id: number;
        createdAt: string;
        clientId: number;
        amount: number;
        dueDate: string;
        description?: string | null | undefined;
        clientName?: string | null | undefined;
        paidAt?: string | null | undefined;
    }, {
        status: string;
        id: number;
        createdAt: string;
        clientId: number;
        amount: number;
        dueDate: string;
        description?: string | null | undefined;
        clientName?: string | null | undefined;
        paidAt?: string | null | undefined;
    }>, "many">;
    total: zod.ZodNumber;
    page: zod.ZodNumber;
    limit: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    page: number;
    limit: number;
    data: {
        status: string;
        id: number;
        createdAt: string;
        clientId: number;
        amount: number;
        dueDate: string;
        description?: string | null | undefined;
        clientName?: string | null | undefined;
        paidAt?: string | null | undefined;
    }[];
    total: number;
}, {
    page: number;
    limit: number;
    data: {
        status: string;
        id: number;
        createdAt: string;
        clientId: number;
        amount: number;
        dueDate: string;
        description?: string | null | undefined;
        clientName?: string | null | undefined;
        paidAt?: string | null | undefined;
    }[];
    total: number;
}>;
/**
 * @summary Create invoice
 */
export declare const CreateInvoiceBody: zod.ZodObject<{
    clientId: zod.ZodNumber;
    amount: zod.ZodNumber;
    description: zod.ZodOptional<zod.ZodString>;
    dueDate: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    clientId: number;
    amount: number;
    dueDate: string;
    description?: string | undefined;
}, {
    clientId: number;
    amount: number;
    dueDate: string;
    description?: string | undefined;
}>;
/**
 * @summary Get invoice by ID
 */
export declare const GetInvoiceParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetInvoiceResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    clientId: zod.ZodNumber;
    clientName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    amount: zod.ZodNumber;
    status: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    dueDate: zod.ZodString;
    paidAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    clientId: number;
    amount: number;
    dueDate: string;
    description?: string | null | undefined;
    clientName?: string | null | undefined;
    paidAt?: string | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    clientId: number;
    amount: number;
    dueDate: string;
    description?: string | null | undefined;
    clientName?: string | null | undefined;
    paidAt?: string | null | undefined;
}>;
/**
 * @summary Update invoice status
 */
export declare const UpdateInvoiceParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateInvoiceBody: zod.ZodObject<{
    status: zod.ZodOptional<zod.ZodString>;
    paidAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status?: string | undefined;
    paidAt?: string | undefined;
}, {
    status?: string | undefined;
    paidAt?: string | undefined;
}>;
export declare const UpdateInvoiceResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    clientId: zod.ZodNumber;
    clientName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    amount: zod.ZodNumber;
    status: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    dueDate: zod.ZodString;
    paidAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    clientId: number;
    amount: number;
    dueDate: string;
    description?: string | null | undefined;
    clientName?: string | null | undefined;
    paidAt?: string | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    clientId: number;
    amount: number;
    dueDate: string;
    description?: string | null | undefined;
    clientName?: string | null | undefined;
    paidAt?: string | null | undefined;
}>;
/**
 * @summary Get financial summary (MRR, ARR, churn)
 */
export declare const GetFinancialSummaryResponse: zod.ZodObject<{
    mrr: zod.ZodNumber;
    arr: zod.ZodNumber;
    totalRevenue: zod.ZodNumber;
    pendingRevenue: zod.ZodNumber;
    overdueAmount: zod.ZodNumber;
    churnRate: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    churnRate: number;
    mrr: number;
    arr: number;
    totalRevenue: number;
    pendingRevenue: number;
    overdueAmount: number;
}, {
    churnRate: number;
    mrr: number;
    arr: number;
    totalRevenue: number;
    pendingRevenue: number;
    overdueAmount: number;
}>;
/**
 * @summary List all support tickets
 */
export declare const ListTicketsQueryParams: zod.ZodObject<{
    status: zod.ZodOptional<zod.ZodString>;
    priority: zod.ZodOptional<zod.ZodString>;
    page: zod.ZodOptional<zod.ZodNumber>;
    limit: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    status?: string | undefined;
    page?: number | undefined;
    limit?: number | undefined;
    priority?: string | undefined;
}, {
    status?: string | undefined;
    page?: number | undefined;
    limit?: number | undefined;
    priority?: string | undefined;
}>;
export declare const ListTicketsResponse: zod.ZodObject<{
    data: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        clientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        clientName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        subject: zod.ZodString;
        description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        status: zod.ZodString;
        priority: zod.ZodString;
        createdAt: zod.ZodString;
        updatedAt: zod.ZodOptional<zod.ZodString>;
    }, "strip", zod.ZodTypeAny, {
        status: string;
        id: number;
        createdAt: string;
        priority: string;
        subject: string;
        description?: string | null | undefined;
        clientName?: string | null | undefined;
        updatedAt?: string | undefined;
        clientId?: number | null | undefined;
    }, {
        status: string;
        id: number;
        createdAt: string;
        priority: string;
        subject: string;
        description?: string | null | undefined;
        clientName?: string | null | undefined;
        updatedAt?: string | undefined;
        clientId?: number | null | undefined;
    }>, "many">;
    total: zod.ZodNumber;
    page: zod.ZodNumber;
    limit: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    page: number;
    limit: number;
    data: {
        status: string;
        id: number;
        createdAt: string;
        priority: string;
        subject: string;
        description?: string | null | undefined;
        clientName?: string | null | undefined;
        updatedAt?: string | undefined;
        clientId?: number | null | undefined;
    }[];
    total: number;
}, {
    page: number;
    limit: number;
    data: {
        status: string;
        id: number;
        createdAt: string;
        priority: string;
        subject: string;
        description?: string | null | undefined;
        clientName?: string | null | undefined;
        updatedAt?: string | undefined;
        clientId?: number | null | undefined;
    }[];
    total: number;
}>;
/**
 * @summary Create a new support ticket
 */
export declare const CreateTicketBody: zod.ZodObject<{
    clientId: zod.ZodOptional<zod.ZodNumber>;
    subject: zod.ZodString;
    description: zod.ZodOptional<zod.ZodString>;
    priority: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    priority: string;
    subject: string;
    description?: string | undefined;
    clientId?: number | undefined;
}, {
    priority: string;
    subject: string;
    description?: string | undefined;
    clientId?: number | undefined;
}>;
/**
 * @summary Get ticket by ID
 */
export declare const GetTicketParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetTicketResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    clientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    clientName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    subject: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodString;
    priority: zod.ZodString;
    createdAt: zod.ZodString;
    updatedAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    priority: string;
    subject: string;
    description?: string | null | undefined;
    clientName?: string | null | undefined;
    updatedAt?: string | undefined;
    clientId?: number | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    priority: string;
    subject: string;
    description?: string | null | undefined;
    clientName?: string | null | undefined;
    updatedAt?: string | undefined;
    clientId?: number | null | undefined;
}>;
/**
 * @summary Update ticket
 */
export declare const UpdateTicketParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateTicketBody: zod.ZodObject<{
    subject: zod.ZodOptional<zod.ZodString>;
    description: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodOptional<zod.ZodString>;
    priority: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status?: string | undefined;
    description?: string | undefined;
    priority?: string | undefined;
    subject?: string | undefined;
}, {
    status?: string | undefined;
    description?: string | undefined;
    priority?: string | undefined;
    subject?: string | undefined;
}>;
export declare const UpdateTicketResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    clientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    clientName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    subject: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodString;
    priority: zod.ZodString;
    createdAt: zod.ZodString;
    updatedAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    priority: string;
    subject: string;
    description?: string | null | undefined;
    clientName?: string | null | undefined;
    updatedAt?: string | undefined;
    clientId?: number | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    priority: string;
    subject: string;
    description?: string | null | undefined;
    clientName?: string | null | undefined;
    updatedAt?: string | undefined;
    clientId?: number | null | undefined;
}>;
/**
 * @summary Close a ticket
 */
export declare const CloseTicketParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const CloseTicketResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    clientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    clientName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    subject: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodString;
    priority: zod.ZodString;
    createdAt: zod.ZodString;
    updatedAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    createdAt: string;
    priority: string;
    subject: string;
    description?: string | null | undefined;
    clientName?: string | null | undefined;
    updatedAt?: string | undefined;
    clientId?: number | null | undefined;
}, {
    status: string;
    id: number;
    createdAt: string;
    priority: string;
    subject: string;
    description?: string | null | undefined;
    clientName?: string | null | undefined;
    updatedAt?: string | undefined;
    clientId?: number | null | undefined;
}>;
/**
 * @summary List all system alerts
 */
export declare const ListAlertsQueryParams: zod.ZodObject<{
    unreadOnly: zod.ZodOptional<zod.ZodBoolean>;
    limit: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    limit?: number | undefined;
    unreadOnly?: boolean | undefined;
}, {
    limit?: number | undefined;
    unreadOnly?: boolean | undefined;
}>;
export declare const ListAlertsResponse: zod.ZodObject<{
    alerts: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        type: zod.ZodString;
        severity: zod.ZodString;
        title: zod.ZodString;
        message: zod.ZodString;
        serverId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        serverName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        read: zod.ZodBoolean;
        createdAt: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        message: string;
        type: string;
        id: number;
        createdAt: string;
        severity: string;
        title: string;
        read: boolean;
        serverId?: number | null | undefined;
        serverName?: string | null | undefined;
    }, {
        message: string;
        type: string;
        id: number;
        createdAt: string;
        severity: string;
        title: string;
        read: boolean;
        serverId?: number | null | undefined;
        serverName?: string | null | undefined;
    }>, "many">;
    unreadCount: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    alerts: {
        message: string;
        type: string;
        id: number;
        createdAt: string;
        severity: string;
        title: string;
        read: boolean;
        serverId?: number | null | undefined;
        serverName?: string | null | undefined;
    }[];
    unreadCount: number;
}, {
    alerts: {
        message: string;
        type: string;
        id: number;
        createdAt: string;
        severity: string;
        title: string;
        read: boolean;
        serverId?: number | null | undefined;
        serverName?: string | null | undefined;
    }[];
    unreadCount: number;
}>;
/**
 * @summary Mark all alerts as read
 */
export declare const MarkAllAlertsReadResponse: zod.ZodObject<{
    updated: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    updated: number;
}, {
    updated: number;
}>;
/**
 * @summary Mark a single alert as read
 */
export declare const MarkAlertReadParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const MarkAlertReadResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    type: zod.ZodString;
    severity: zod.ZodString;
    title: zod.ZodString;
    message: zod.ZodString;
    serverId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    serverName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    read: zod.ZodBoolean;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    message: string;
    type: string;
    id: number;
    createdAt: string;
    severity: string;
    title: string;
    read: boolean;
    serverId?: number | null | undefined;
    serverName?: string | null | undefined;
}, {
    message: string;
    type: string;
    id: number;
    createdAt: string;
    severity: string;
    title: string;
    read: boolean;
    serverId?: number | null | undefined;
    serverName?: string | null | undefined;
}>;
/**
 * @summary Run a server health check and generate alerts for issues
 */
export declare const CheckServerAlertsResponse: zod.ZodObject<{
    generated: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    generated: number;
}, {
    generated: number;
}>;
//# sourceMappingURL=api.d.ts.map