/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * IPTV/OTT SaaS Platform API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Get main dashboard statistics
 */
export const GetDashboardStatsResponse = zod.object({
  "totalClients": zod.number(),
  "activeSubscriptions": zod.number(),
  "monthlyRevenue": zod.number(),
  "activeServers": zod.number(),
  "newClientsThisMonth": zod.number(),
  "churnRate": zod.number(),
  "openTickets": zod.number(),
  "totalResellers": zod.number()
})


/**
 * @summary Get revenue chart data (last 12 months)
 */
export const GetRevenueChartResponseItem = zod.object({
  "month": zod.string(),
  "revenue": zod.number(),
  "subscriptions": zod.number()
})
export const GetRevenueChartResponse = zod.array(GetRevenueChartResponseItem)


/**
 * @summary Get recent activity feed
 */
export const GetRecentActivityResponseItem = zod.object({
  "id": zod.number(),
  "type": zod.string(),
  "description": zod.string(),
  "clientName": zod.string().nullish(),
  "createdAt": zod.string()
})
export const GetRecentActivityResponse = zod.array(GetRecentActivityResponseItem)


/**
 * @summary Get subscription status breakdown
 */
export const GetSubscriptionBreakdownResponseItem = zod.object({
  "status": zod.string(),
  "count": zod.number(),
  "percentage": zod.number()
})
export const GetSubscriptionBreakdownResponse = zod.array(GetSubscriptionBreakdownResponseItem)


/**
 * @summary List all clients
 */
export const ListClientsQueryParams = zod.object({
  "search": zod.coerce.string().optional(),
  "status": zod.coerce.string().optional(),
  "page": zod.coerce.number().optional(),
  "limit": zod.coerce.number().optional()
})

export const ListClientsResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().nullish(),
  "status": zod.string(),
  "resellerId": zod.number().nullish(),
  "resellerName": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string().optional()
})),
  "total": zod.number(),
  "page": zod.number(),
  "limit": zod.number()
})


/**
 * @summary Create a new client
 */
export const CreateClientBody = zod.object({
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().optional(),
  "resellerId": zod.number().optional(),
  "notes": zod.string().optional()
})


/**
 * @summary Get client by ID
 */
export const GetClientParams = zod.object({
  "id": zod.coerce.number()
})

export const GetClientResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().nullish(),
  "status": zod.string(),
  "resellerId": zod.number().nullish(),
  "resellerName": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string().optional()
})


/**
 * @summary Update client
 */
export const UpdateClientParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateClientBody = zod.object({
  "name": zod.string().optional(),
  "email": zod.string().optional(),
  "phone": zod.string().optional(),
  "status": zod.string().optional(),
  "resellerId": zod.number().optional(),
  "notes": zod.string().optional()
})

export const UpdateClientResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().nullish(),
  "status": zod.string(),
  "resellerId": zod.number().nullish(),
  "resellerName": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string().optional()
})


/**
 * @summary Delete client
 */
export const DeleteClientParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary Suspend client account
 */
export const SuspendClientParams = zod.object({
  "id": zod.coerce.number()
})

export const SuspendClientResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().nullish(),
  "status": zod.string(),
  "resellerId": zod.number().nullish(),
  "resellerName": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string().optional()
})


/**
 * @summary Activate client account
 */
export const ActivateClientParams = zod.object({
  "id": zod.coerce.number()
})

export const ActivateClientResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().nullish(),
  "status": zod.string(),
  "resellerId": zod.number().nullish(),
  "resellerName": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string().optional()
})


/**
 * @summary Bulk import clients from CSV data
 */
export const ImportClientsBody = zod.object({
  "csv": zod.string(),
  "skipErrors": zod.boolean().optional()
})

export const ImportClientsResponse = zod.object({
  "imported": zod.number(),
  "skipped": zod.number(),
  "errors": zod.array(zod.object({
  "row": zod.number(),
  "reason": zod.string(),
  "data": zod.string().optional()
}))
})


/**
 * @summary List all plans
 */
export const ListPlansResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "durationDays": zod.number(),
  "maxConnections": zod.number(),
  "features": zod.string().nullish(),
  "creditCost": zod.number().nullish(),
  "status": zod.string(),
  "createdAt": zod.string()
})
export const ListPlansResponse = zod.array(ListPlansResponseItem)


/**
 * @summary Create a new plan
 */
export const CreatePlanBody = zod.object({
  "name": zod.string(),
  "description": zod.string().optional(),
  "price": zod.number(),
  "durationDays": zod.number(),
  "maxConnections": zod.number(),
  "features": zod.string().optional(),
  "creditCost": zod.number().optional()
})


/**
 * @summary Get plan by ID
 */
export const GetPlanParams = zod.object({
  "id": zod.coerce.number()
})

export const GetPlanResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "durationDays": zod.number(),
  "maxConnections": zod.number(),
  "features": zod.string().nullish(),
  "creditCost": zod.number().nullish(),
  "status": zod.string(),
  "createdAt": zod.string()
})


/**
 * @summary Update plan
 */
export const UpdatePlanParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdatePlanBody = zod.object({
  "name": zod.string().optional(),
  "description": zod.string().optional(),
  "price": zod.number().optional(),
  "durationDays": zod.number().optional(),
  "maxConnections": zod.number().optional(),
  "features": zod.string().optional(),
  "creditCost": zod.number().optional(),
  "status": zod.string().optional()
})

export const UpdatePlanResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "durationDays": zod.number(),
  "maxConnections": zod.number(),
  "features": zod.string().nullish(),
  "creditCost": zod.number().nullish(),
  "status": zod.string(),
  "createdAt": zod.string()
})


/**
 * @summary Delete plan
 */
export const DeletePlanParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary List all subscriptions
 */
export const ListSubscriptionsQueryParams = zod.object({
  "status": zod.coerce.string().optional(),
  "clientId": zod.coerce.number().optional(),
  "page": zod.coerce.number().optional(),
  "limit": zod.coerce.number().optional()
})

export const ListSubscriptionsResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.number(),
  "clientId": zod.number(),
  "clientName": zod.string().nullish(),
  "planId": zod.number(),
  "planName": zod.string().nullish(),
  "serverId": zod.number().nullish(),
  "serverName": zod.string().nullish(),
  "status": zod.string(),
  "username": zod.string().nullish(),
  "password": zod.string().nullish(),
  "startDate": zod.string(),
  "endDate": zod.string(),
  "createdAt": zod.string()
})),
  "total": zod.number(),
  "page": zod.number(),
  "limit": zod.number()
})


/**
 * @summary Create a new subscription
 */
export const CreateSubscriptionBody = zod.object({
  "clientId": zod.number(),
  "planId": zod.number(),
  "serverId": zod.number().optional(),
  "username": zod.string().optional(),
  "password": zod.string().optional(),
  "startDate": zod.string()
})


/**
 * @summary Get subscription by ID
 */
export const GetSubscriptionParams = zod.object({
  "id": zod.coerce.number()
})

export const GetSubscriptionResponse = zod.object({
  "id": zod.number(),
  "clientId": zod.number(),
  "clientName": zod.string().nullish(),
  "planId": zod.number(),
  "planName": zod.string().nullish(),
  "serverId": zod.number().nullish(),
  "serverName": zod.string().nullish(),
  "status": zod.string(),
  "username": zod.string().nullish(),
  "password": zod.string().nullish(),
  "startDate": zod.string(),
  "endDate": zod.string(),
  "createdAt": zod.string()
})


/**
 * @summary Update subscription
 */
export const UpdateSubscriptionParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateSubscriptionBody = zod.object({
  "planId": zod.number().optional(),
  "serverId": zod.number().optional(),
  "status": zod.string().optional(),
  "username": zod.string().optional(),
  "password": zod.string().optional(),
  "endDate": zod.string().optional()
})

export const UpdateSubscriptionResponse = zod.object({
  "id": zod.number(),
  "clientId": zod.number(),
  "clientName": zod.string().nullish(),
  "planId": zod.number(),
  "planName": zod.string().nullish(),
  "serverId": zod.number().nullish(),
  "serverName": zod.string().nullish(),
  "status": zod.string(),
  "username": zod.string().nullish(),
  "password": zod.string().nullish(),
  "startDate": zod.string(),
  "endDate": zod.string(),
  "createdAt": zod.string()
})


/**
 * @summary Cancel subscription
 */
export const DeleteSubscriptionParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary Renew subscription
 */
export const RenewSubscriptionParams = zod.object({
  "id": zod.coerce.number()
})

export const RenewSubscriptionResponse = zod.object({
  "id": zod.number(),
  "clientId": zod.number(),
  "clientName": zod.string().nullish(),
  "planId": zod.number(),
  "planName": zod.string().nullish(),
  "serverId": zod.number().nullish(),
  "serverName": zod.string().nullish(),
  "status": zod.string(),
  "username": zod.string().nullish(),
  "password": zod.string().nullish(),
  "startDate": zod.string(),
  "endDate": zod.string(),
  "createdAt": zod.string()
})


/**
 * @summary List all IPTV servers
 */
export const ListServersResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "host": zod.string(),
  "port": zod.number(),
  "username": zod.string().nullish(),
  "password": zod.string().nullish(),
  "status": zod.string(),
  "maxConnections": zod.number().nullish(),
  "activeStreams": zod.number().optional(),
  "location": zod.string().nullish(),
  "createdAt": zod.string()
})
export const ListServersResponse = zod.array(ListServersResponseItem)


/**
 * @summary Add a new IPTV server
 */
export const CreateServerBody = zod.object({
  "name": zod.string(),
  "host": zod.string(),
  "port": zod.number(),
  "username": zod.string().optional(),
  "password": zod.string().optional(),
  "maxConnections": zod.number().optional(),
  "location": zod.string().optional()
})


/**
 * @summary Get server by ID
 */
export const GetServerParams = zod.object({
  "id": zod.coerce.number()
})

export const GetServerResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "host": zod.string(),
  "port": zod.number(),
  "username": zod.string().nullish(),
  "password": zod.string().nullish(),
  "status": zod.string(),
  "maxConnections": zod.number().nullish(),
  "activeStreams": zod.number().optional(),
  "location": zod.string().nullish(),
  "createdAt": zod.string()
})


/**
 * @summary Update server
 */
export const UpdateServerParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateServerBody = zod.object({
  "name": zod.string().optional(),
  "host": zod.string().optional(),
  "port": zod.number().optional(),
  "username": zod.string().optional(),
  "password": zod.string().optional(),
  "status": zod.string().optional(),
  "maxConnections": zod.number().optional(),
  "location": zod.string().optional()
})

export const UpdateServerResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "host": zod.string(),
  "port": zod.number(),
  "username": zod.string().nullish(),
  "password": zod.string().nullish(),
  "status": zod.string(),
  "maxConnections": zod.number().nullish(),
  "activeStreams": zod.number().optional(),
  "location": zod.string().nullish(),
  "createdAt": zod.string()
})


/**
 * @summary Delete server
 */
export const DeleteServerParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary Get health metrics for all IPTV servers
 */
export const GetServersHealthResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "host": zod.string(),
  "port": zod.number(),
  "status": zod.string(),
  "location": zod.string().nullable(),
  "activeStreams": zod.number(),
  "maxConnections": zod.number().nullable(),
  "loadPct": zod.number(),
  "latencyMs": zod.number().nullable(),
  "checkedAt": zod.string()
})
export const GetServersHealthResponse = zod.array(GetServersHealthResponseItem)


/**
 * @summary Test server connectivity
 */
export const TestServerParams = zod.object({
  "id": zod.coerce.number()
})

export const TestServerResponse = zod.object({
  "online": zod.boolean(),
  "latencyMs": zod.number().nullable(),
  "message": zod.string()
})


/**
 * @summary List all resellers
 */
export const ListResellersQueryParams = zod.object({
  "search": zod.coerce.string().optional(),
  "status": zod.coerce.string().optional(),
  "page": zod.coerce.number().optional(),
  "limit": zod.coerce.number().optional()
})

export const ListResellersResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().nullish(),
  "status": zod.string(),
  "creditBalance": zod.number(),
  "totalClients": zod.number().optional(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string()
})),
  "total": zod.number(),
  "page": zod.number(),
  "limit": zod.number()
})


/**
 * @summary Create a new reseller
 */
export const CreateResellerBody = zod.object({
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().optional(),
  "creditBalance": zod.number().optional(),
  "notes": zod.string().optional()
})


/**
 * @summary Get reseller by ID
 */
export const GetResellerParams = zod.object({
  "id": zod.coerce.number()
})

export const GetResellerResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().nullish(),
  "status": zod.string(),
  "creditBalance": zod.number(),
  "totalClients": zod.number().optional(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string()
})


/**
 * @summary Update reseller
 */
export const UpdateResellerParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateResellerBody = zod.object({
  "name": zod.string().optional(),
  "email": zod.string().optional(),
  "phone": zod.string().optional(),
  "status": zod.string().optional(),
  "notes": zod.string().optional()
})

export const UpdateResellerResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().nullish(),
  "status": zod.string(),
  "creditBalance": zod.number(),
  "totalClients": zod.number().optional(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string()
})


/**
 * @summary Delete reseller
 */
export const DeleteResellerParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary Adjust reseller credit balance
 */
export const AdjustResellerCreditsParams = zod.object({
  "id": zod.coerce.number()
})

export const AdjustResellerCreditsBody = zod.object({
  "amount": zod.number(),
  "reason": zod.string()
})

export const AdjustResellerCreditsResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().nullish(),
  "status": zod.string(),
  "creditBalance": zod.number(),
  "totalClients": zod.number().optional(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string()
})


/**
 * @summary Get platform settings
 */
export const GetSettingsResponse = zod.object({
  "operationMode": zod.string(),
  "creditCurrencyName": zod.string(),
  "creditToMoneyRate": zod.number()
})


/**
 * @summary Update platform settings
 */
export const UpdateSettingsBody = zod.object({
  "operationMode": zod.string().optional(),
  "creditCurrencyName": zod.string().optional(),
  "creditToMoneyRate": zod.number().optional()
})

export const UpdateSettingsResponse = zod.object({
  "operationMode": zod.string(),
  "creditCurrencyName": zod.string(),
  "creditToMoneyRate": zod.number()
})


/**
 * @summary List all credit transactions
 */
export const ListCreditTransactionsQueryParams = zod.object({
  "resellerId": zod.coerce.number().optional(),
  "type": zod.coerce.string().optional(),
  "page": zod.coerce.number().optional(),
  "limit": zod.coerce.number().optional()
})

export const ListCreditTransactionsResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.number(),
  "resellerId": zod.number(),
  "resellerName": zod.string(),
  "type": zod.string(),
  "amount": zod.number(),
  "balanceAfter": zod.number(),
  "description": zod.string(),
  "createdAt": zod.string()
})),
  "total": zod.number(),
  "page": zod.number(),
  "limit": zod.number(),
  "totalPurchased": zod.number(),
  "totalDeducted": zod.number()
})


/**
 * @summary Get credit summary stats
 */
export const GetCreditSummaryResponse = zod.object({
  "totalCreditsInCirculation": zod.number(),
  "purchasedThisMonth": zod.number(),
  "deductedThisMonth": zod.number(),
  "topResellers": zod.array(zod.object({
  "resellerId": zod.number(),
  "resellerName": zod.string(),
  "creditBalance": zod.number()
}))
})


/**
 * @summary List all invoices
 */
export const ListInvoicesQueryParams = zod.object({
  "status": zod.coerce.string().optional(),
  "clientId": zod.coerce.number().optional(),
  "page": zod.coerce.number().optional(),
  "limit": zod.coerce.number().optional()
})

export const ListInvoicesResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.number(),
  "clientId": zod.number(),
  "clientName": zod.string().nullish(),
  "amount": zod.number(),
  "status": zod.string(),
  "description": zod.string().nullish(),
  "dueDate": zod.string(),
  "paidAt": zod.string().nullish(),
  "createdAt": zod.string()
})),
  "total": zod.number(),
  "page": zod.number(),
  "limit": zod.number()
})


/**
 * @summary Create invoice
 */
export const CreateInvoiceBody = zod.object({
  "clientId": zod.number(),
  "amount": zod.number(),
  "description": zod.string().optional(),
  "dueDate": zod.string()
})


/**
 * @summary Get invoice by ID
 */
export const GetInvoiceParams = zod.object({
  "id": zod.coerce.number()
})

export const GetInvoiceResponse = zod.object({
  "id": zod.number(),
  "clientId": zod.number(),
  "clientName": zod.string().nullish(),
  "amount": zod.number(),
  "status": zod.string(),
  "description": zod.string().nullish(),
  "dueDate": zod.string(),
  "paidAt": zod.string().nullish(),
  "createdAt": zod.string()
})


/**
 * @summary Update invoice status
 */
export const UpdateInvoiceParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateInvoiceBody = zod.object({
  "status": zod.string().optional(),
  "paidAt": zod.string().optional()
})

export const UpdateInvoiceResponse = zod.object({
  "id": zod.number(),
  "clientId": zod.number(),
  "clientName": zod.string().nullish(),
  "amount": zod.number(),
  "status": zod.string(),
  "description": zod.string().nullish(),
  "dueDate": zod.string(),
  "paidAt": zod.string().nullish(),
  "createdAt": zod.string()
})


/**
 * @summary Get financial summary (MRR, ARR, churn)
 */
export const GetFinancialSummaryResponse = zod.object({
  "mrr": zod.number(),
  "arr": zod.number(),
  "totalRevenue": zod.number(),
  "pendingRevenue": zod.number(),
  "overdueAmount": zod.number(),
  "churnRate": zod.number()
})


/**
 * @summary List all support tickets
 */
export const ListTicketsQueryParams = zod.object({
  "status": zod.coerce.string().optional(),
  "priority": zod.coerce.string().optional(),
  "page": zod.coerce.number().optional(),
  "limit": zod.coerce.number().optional()
})

export const ListTicketsResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.number(),
  "clientId": zod.number().nullish(),
  "clientName": zod.string().nullish(),
  "subject": zod.string(),
  "description": zod.string().nullish(),
  "status": zod.string(),
  "priority": zod.string(),
  "createdAt": zod.string(),
  "updatedAt": zod.string().optional()
})),
  "total": zod.number(),
  "page": zod.number(),
  "limit": zod.number()
})


/**
 * @summary Create a new support ticket
 */
export const CreateTicketBody = zod.object({
  "clientId": zod.number().optional(),
  "subject": zod.string(),
  "description": zod.string().optional(),
  "priority": zod.string()
})


/**
 * @summary Get ticket by ID
 */
export const GetTicketParams = zod.object({
  "id": zod.coerce.number()
})

export const GetTicketResponse = zod.object({
  "id": zod.number(),
  "clientId": zod.number().nullish(),
  "clientName": zod.string().nullish(),
  "subject": zod.string(),
  "description": zod.string().nullish(),
  "status": zod.string(),
  "priority": zod.string(),
  "createdAt": zod.string(),
  "updatedAt": zod.string().optional()
})


/**
 * @summary Update ticket
 */
export const UpdateTicketParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateTicketBody = zod.object({
  "subject": zod.string().optional(),
  "description": zod.string().optional(),
  "status": zod.string().optional(),
  "priority": zod.string().optional()
})

export const UpdateTicketResponse = zod.object({
  "id": zod.number(),
  "clientId": zod.number().nullish(),
  "clientName": zod.string().nullish(),
  "subject": zod.string(),
  "description": zod.string().nullish(),
  "status": zod.string(),
  "priority": zod.string(),
  "createdAt": zod.string(),
  "updatedAt": zod.string().optional()
})


/**
 * @summary Close a ticket
 */
export const CloseTicketParams = zod.object({
  "id": zod.coerce.number()
})

export const CloseTicketResponse = zod.object({
  "id": zod.number(),
  "clientId": zod.number().nullish(),
  "clientName": zod.string().nullish(),
  "subject": zod.string(),
  "description": zod.string().nullish(),
  "status": zod.string(),
  "priority": zod.string(),
  "createdAt": zod.string(),
  "updatedAt": zod.string().optional()
})


/**
 * @summary List all system alerts
 */
export const ListAlertsQueryParams = zod.object({
  "unreadOnly": zod.coerce.boolean().optional(),
  "limit": zod.coerce.number().optional()
})

export const ListAlertsResponse = zod.object({
  "alerts": zod.array(zod.object({
  "id": zod.number(),
  "type": zod.string(),
  "severity": zod.string(),
  "title": zod.string(),
  "message": zod.string(),
  "serverId": zod.number().nullish(),
  "serverName": zod.string().nullish(),
  "read": zod.boolean(),
  "createdAt": zod.string()
})),
  "unreadCount": zod.number()
})


/**
 * @summary Mark all alerts as read
 */
export const MarkAllAlertsReadResponse = zod.object({
  "updated": zod.number()
})


/**
 * @summary Mark a single alert as read
 */
export const MarkAlertReadParams = zod.object({
  "id": zod.coerce.number()
})

export const MarkAlertReadResponse = zod.object({
  "id": zod.number(),
  "type": zod.string(),
  "severity": zod.string(),
  "title": zod.string(),
  "message": zod.string(),
  "serverId": zod.number().nullish(),
  "serverName": zod.string().nullish(),
  "read": zod.boolean(),
  "createdAt": zod.string()
})


/**
 * @summary Run a server health check and generate alerts for issues
 */
export const CheckServerAlertsResponse = zod.object({
  "generated": zod.number()
})


