/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * IPTV/OTT SaaS Platform API
 * OpenAPI spec version: 0.1.0
 */

export type ClientImportResultErrorsItem = {
  row: number;
  reason: string;
  data?: string;
};
