/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * IPTV/OTT SaaS Platform API
 * OpenAPI spec version: 0.1.0
 */

export interface Client {
  id: number;
  name: string;
  email: string;
  /** @nullable */
  phone?: string | null;
  status: string;
  /** @nullable */
  resellerId?: number | null;
  /** @nullable */
  resellerName?: string | null;
  /** @nullable */
  notes?: string | null;
  createdAt: string;
  updatedAt?: string;
}
