/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * IPTV/OTT SaaS Platform API
 * OpenAPI spec version: 0.1.0
 */

export interface CreditTransaction {
  id: number;
  resellerId: number;
  resellerName: string;
  type: string;
  amount: number;
  balanceAfter: number;
  description: string;
  createdAt: string;
}
