/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * IPTV/OTT SaaS Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { CreditTransaction } from './creditTransaction';

export interface CreditTransactionListResponse {
  data: CreditTransaction[];
  total: number;
  page: number;
  limit: number;
  totalPurchased: number;
  totalDeducted: number;
}
