/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * IPTV/OTT SaaS Platform API
 * OpenAPI spec version: 0.1.0
 */

export interface DashboardStats {
  totalClients: number;
  activeSubscriptions: number;
  monthlyRevenue: number;
  activeServers: number;
  newClientsThisMonth: number;
  churnRate: number;
  openTickets: number;
  totalResellers: number;
}
