/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * IPTV/OTT SaaS Platform API
 * OpenAPI spec version: 0.1.0
 */

export interface Invoice {
  id: number;
  clientId: number;
  /** @nullable */
  clientName?: string | null;
  amount: number;
  status: string;
  /** @nullable */
  description?: string | null;
  dueDate: string;
  /** @nullable */
  paidAt?: string | null;
  createdAt: string;
}
