/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * IPTV/OTT SaaS Platform API
 * OpenAPI spec version: 0.1.0
 */

export interface IptvServer {
  id: number;
  name: string;
  host: string;
  port: number;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  password?: string | null;
  status: string;
  /** @nullable */
  maxConnections?: number | null;
  activeStreams?: number;
  /** @nullable */
  location?: string | null;
  createdAt: string;
}
