/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * IPTV/OTT SaaS Platform API
 * OpenAPI spec version: 0.1.0
 */

export type ListResellersParams = {
search?: string;
status?: string;
page?: number;
limit?: number;
};
