/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * IPTV/OTT SaaS Platform API
 * OpenAPI spec version: 0.1.0
 */

export interface Plan {
  id: number;
  name: string;
  /** @nullable */
  description?: string | null;
  price: number;
  durationDays: number;
  maxConnections: number;
  /** @nullable */
  features?: string | null;
  /** @nullable */
  creditCost?: number | null;
  status: string;
  createdAt: string;
}
