/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * IPTV/OTT SaaS Platform API
 * OpenAPI spec version: 0.1.0
 */

export interface Reseller {
  id: number;
  name: string;
  email: string;
  /** @nullable */
  phone?: string | null;
  status: string;
  creditBalance: number;
  totalClients?: number;
  /** @nullable */
  notes?: string | null;
  createdAt: string;
}
